services:
  bingo:
    container_name: bingo
    image: bingo:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bingo.tls=true"
      - "traefik.http.routers.bingo.entrypoints=websecure"
      - "traefik.http.routers.bingo.rule=Host(`bingo.valdum.dev`)"