apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
    name: bingo
    annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure

spec:
    ingressClassName: traefik
    rules:
      - host: bingo.lan
        http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                    service:
                        name: bingo
                        port:
                            name: http-out

---
apiVersion: v1
kind: Service

metadata:
    name: bingo

spec:
    type: ClusterIP
    selector:
        app: bingo
    sessionAffinity: None
    ports:
      - name: http-out
        protocol: TCP
        port: 80
        targetPort: http-in

---
apiVersion: v1
kind: ConfigMap

metadata:
    name: bingo-nginx-config

data:
    default.conf: |
        server {
            listen       8080;
            listen       [::]:8080;
            server_name  localhost;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;

                # Need for direct path navigation in Flutter
                try_files $uri $uri/ $uri.html /index.html;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }

---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: bingo

spec:
    replicas: 1
    minReadySeconds: 15
    revisionHistoryLimit: 1

    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0

    selector:
        matchLabels:
            app: bingo

    template:
        metadata:
            labels:
                app: bingo

        spec:
            containers:
              - name: bingo
                image: ghcr.io/v4ldum/bingo:latest
                imagePullPolicy: Always

                ports:
                  - name: http-in
                    containerPort: 8080

                env:
                  - name: TZ
                    value: Europe/Paris

                startupProbe:
                    httpGet:
                        path: /
                        port: http-in
                livenessProbe:
                    httpGet:
                        path: /
                        port: http-in
                readinessProbe:
                    timeoutSeconds: 3
                    httpGet:
                        path: /
                        port: http-in

                volumeMounts:
                  - name: config
                    mountPath: /etc/nginx/conf.d/default.conf
                    readOnly: true

            volumes:
              - name: config
                configMap:
                    name: bingo-nginx-config
